SYMBOL = "XAUUSDm"
MAGIC_NUMBER = 20260608
MAGIC_NUMBER_M5 = 20260609
LOT_SIZE = 0.01
MAX_SPREAD_USD = 2.5
SPREAD_DEDUCTION_USD = 0.15
MAX_CONCURRENT_POSITIONS = 1

EMA_FAST, EMA_MED, EMA_SLOW = 5, 21, 200
H1_EMA_PERIOD, RSI_PERIOD, ATR_PERIOD = 50, 7, 14
ADX_PERIOD, VOL_EMA_PERIOD = 14, 10
RSI_PERIOD_M1, RSI_LIMIT_UP_M1, RSI_LIMIT_DOWN_M1 = 7, 80, 20


# Layering Strategy Config
LAYERING_MODE = "USD"  # "USD" or "ATR"
LAYERING_STEP_ATR_MULT = 1.5
LAYERING_STEP_USD = 10.0
TAKE_PROFIT_PER_LAYER_USD = 0.20
MAX_LAYERS = None  # None for unlimited
EXIT_LOGIC_AND = True  # True: both RSI & close conditions; False: either condition
number_of_normal_layer = 5
constant = 2

# Low risk overrides (used outside peak hours on weekdays)
LOW_RISK_OVERRIDES = {
    "LOT_SIZE": 0.01,
    "LAYERING_STEP_ATR_MULT": 1.0,
    "TAKE_PROFIT_PER_LAYER_USD": 0.20,
}

# Moderate risk overrides
MODERATE_RISK_OVERRIDES = {
    "LOT_SIZE": 0.01,
    "LAYERING_STEP_ATR_MULT": 1.25,
    "TAKE_PROFIT_PER_LAYER_USD": 0.20,
}
